<?php
$flex_video = [
    'key' => 'flex_video',
    'name' => 'video',
    'label' => 'Video',
    'display' => 'block',
    'sub_fields' => array (
            array (
                    'key' => 'field_video_poster',
                    'label' => 'Video\'s poster',
                    'name' => 'video_poster',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
            ),
            array (
                    'key' => 'field_video_youtube_id',
                    'label' => 'Youtube video id',
                    'name' => 'video_youtube_id',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
            ),
    ),
    'min' => '',
    'max' => '',
];
